### ISSUE TITLE
Can’t compile out of the box

### ISSUE THREAD

**Issue by alex-taffe** [lbrndnr/nuage-macos#3] opened 2021-01-29 20:37 UTC
The `SoundCloud` library and `StackNavigationView` seem to not be committed to git. They should probably use the swift package manager instead. I can submit a PR for this, but wasnt sure if there was a reason why this was done this way

**Comment by lbrndnr** [comment] 2021-01-29 21:09
Yeah you're right of course. The problem is that as far as I know, the swift package manager does not allow local repositories, at least not in a particularly useful way. This made it a bit difficult to work on these two frameworks.
I wasn't expecting anybody to contribute to Nuage this quickly so I guess I will add them again via the swift package manager :)

**Comment by alex-taffe** [comment] 2021-01-29 21:12
@lbrndnr You actually can. If you just drag the package folder into Xcode on the sidebar, it’ll add it as a local repo and it functions the same way as a remote one. Or just setup git submodules

**Comment by lbrndnr** [comment] 2021-01-29 21:18
Gimme one sec, I have it fixed in a moment

**Comment by lbrndnr** [comment] 2021-01-29 21:36
This should be working now. Let me know if you have any other issues :)

**Closed by lbrndnr** 2021-01-29 21:36 UTC

**Comment by swiatrzyk** [comment] 2024-05-03 14:08
Can't compile for the same reason (missing SoundCloud framework)

**Comment by lbrndnr** [comment] 2024-05-03 15:48
@swiatrzyk you can use `https://github.com/lbrndnr/nuage-macos` to checkout SoundCloud framework as well. It's a git submodule :)

**Comment by swiatrzyk** [comment] 2024-05-03 17:01
Thanks, problem solved 👍🏼
